### ISSUE TITLE
При добавлении жанра игры в которую играли больше всего, метод всегда возвращает null

### ISSUE THREAD

**Issue by Korartol** [ChukharevIlya/JavaQaTeamDiplom#3]
# Описание
Метод не возвращает игру жанра в который играли больше всего, ответ всегда null, т.к. метод не реализован.

# Локация дефекта
https://github.com/ChukharevIlya/JavaQaTeamDiplom/blob/9e59e91b6f760e0ef82b4965530d04fdd0307fac/src/main/java/ru/netology/Player.java#L57-L61

# Шаги воспроизведения

1. Открыть код из локации дефекта.
2. Убедиться что он всегда возвращает null

* Ожидаемый результат - метод возвращает игру из жанра, в которую играли больше всего
* Фактический результат - метод всегда будет возвращать null, т.к. другого в методе не задано.

# Скриншот
<img width="677" alt="Снимок экрана 2022-08-15 в 10 24 33" src="https://user-images.githubusercontent.com/102210294/184593557-ab7723cd-6197-4ed2-9c04-327548fcbaa4.png">

<img width="750" alt="Снимок экрана 2022-08-15 в 10 40 17" src="https://user-images.githubusercontent.com/102210294/184595524-a9407743-ffc5-4b59-8b89-1741211b6bda.png">

# Окружение
* **Операционная система:** MacOS Monterey
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by ChukharevIlya** [comment]
метод реализован https://github.com/ChukharevIlya/JavaQaTeamDiplom/commit/903017ef9e12eff20bd143d6bc39f66c54af532c
